import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import LoginModal from "../components/LoginModal";

export default function Home() {
  const [modal, setModal] = useState(false);

  const clickModal = () => {
    setModal(true);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.main}>
          <div className={styles.main_input_img}>
            <img
              className={styles.main_input_img_icon}
              src="./img/Icon.png"
              alt="이미지 테스트"
            ></img>
            <span>가지마켓</span>
          </div>
          <div className={styles.main_input}>
            <div>
              <input
                className={styles.main_input_id}
                type="text"
                placeholder="아이디를 입력하시오"
              ></input>
              <input
                className={styles.main_input_pw}
                type="text"
                placeholder="비밃번호를 입력하시오"
              ></input>
              <div className={styles.main_input_text}>
                <span>회원가입</span>
                <span>로그인</span>
              </div>
              <div className={styles.main_input_btn}>
                <button onClick={clickModal}>로그인</button>
              </div>
            </div>
            {modal && <LoginModal />}
          </div>
        </div>
      </main>
    </>
  );
}
